feat: Enable Keda autoscaling on ingress controller
pagopa/devopslab-infra pull request #21
Opened 2022-04-14 06:07 UTC by matteocellucci

### List of changes

### Motivation and context

### Type of changes

- [x] Add new resources
- [x] Update configuration to existing resources
- [ ] Remove existing resources

### Env to apply

- [x] DEV
- [ ] UAT
- [ ] PROD

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

### Other information

---

### If PR is partially applied, why? (reserved to mantainers)

2022-04-14 10:17 UTC, diegolagospagopa requested changes

2022-04-14 10:17 UTC, diegolagospagopa commented on src/k8s/ingress/autoscaling.yaml.tpl
> +    maxReplicas: 4
can we set dynamically this parameters?

2022-04-14 10:18 UTC, diegolagospagopa commented on src/k8s/ingress/autoscaling.yaml.tpl
> +          targetValue: "30"
This metric will be changed or can be dynamic?

2022-05-16 09:15 UTC, pasqualedevita approved these changes

2022-05-16 09:16 UTC, merged